apiVersion: v1
kind: Service
metadata:
  name: nodeserv
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 80
      nodePort: 30300
  externalIPs:
    - 198.51.100.32
