apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tomcat-rpset


spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      name: tomcat-pod
      labels:
        app: tomcat
    spec:
      containers:
       - name: tom-container
         image: tomcat:9.0

