apiVersion: v1
kind: Service
metadata:
  name: repset-np
spec:
  type: NodePort
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 8080
      nodePort: 30301
  externalIPs:
    - 198.51.100.32
